### ISSUE TITLE
Need help with HTTP mode

### ISSUE THREAD

**Issue by Cnzw** [owntracks/talk#212]
Hello,

I'm currently deploying owntracks/recorder:0.9.9 using Docker. I can successfully access the Recorder via the web interface, but I'm encountering issues when trying to use the OwnTracks app on my Android device.

I noticed that the [Quicksetup guide](https://owntracks.org/booklet/guide/quicksetup/) mentions the need to configure configuration.yaml and run bootstrap.sh to set up the OwnTracks environment. However, I couldn't find any reference to these steps in the [Docker repository](https://github.com/owntracks/docker-recorder).

![Image](https://github.com/user-attachments/assets/86f64a84-623e-4058-99a1-f06207c55199)

![Image](https://github.com/user-attachments/assets/0ebab2df-9ee7-4363-884d-944f66e702dc)

```yaml
version: "3"
services:

    otrecorder:
        image: owntracks/recorder:0.9.9
        environment:
            - TZ=Asia/Shanghai
            - OTR_PORT=0
        volumes:
            - /www/docker/owntracks/recorder:/store
        ports:
            - 8083:8083
        container_name: otrecorder
        restart: unless-stopped
```
